/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.Bida.form;

import com.Bida.swing.Customers;
import com.Bida.swing.CustomersDAO;
import java.awt.Image;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Form_Customers extends javax.swing.JPanel {
    CustomersDAO dao = new CustomersDAO();
    String strImage = null;
    /**
     * Creates new form Form_Customers
     */
    public Form_Customers() {
        initComponents();
    }
    public void fillTable(){
        DefaultTableModel model = (DefaultTableModel)dataCUSTOMER.getModel();
        model.setRowCount(0);
        for(Customers cus : dao.getAllCustomer()){
            Object rowData[] = new Object[5];
            rowData[0] = cus.getId();
            rowData[1] = cus.getName();
            rowData[2] = cus.getPhone();
            rowData[3] = cus.isGender()?"MALE":"FEMALE";
            rowData[4] = cus.getImage();
            model.addRow(rowData);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataCUSTOMER = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        btADD = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ibImage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        gdMale = new javax.swing.JRadioButton();
        btEDIT = new javax.swing.JButton();
        gdFemale = new javax.swing.JRadioButton();
        btDELETE = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        btSAVE = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Data Customers:");

        dataCUSTOMER.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "PHONE", "GENDER", "IMAGE"
            }
        ));
        dataCUSTOMER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataCUSTOMERMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataCUSTOMER);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID:");

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        btADD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btADD.setText("ADD");
        btADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btADDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Fullname:");

        ibImage.setBackground(new java.awt.Color(204, 255, 255));
        ibImage.setText("Image");
        ibImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ibImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ibImageMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Phone:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Gender:");

        buttonGroup1.add(gdMale);
        gdMale.setSelected(true);
        gdMale.setText("Male");
        gdMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gdMaleActionPerformed(evt);
            }
        });

        btEDIT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btEDIT.setText("EDIT");
        btEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEDITActionPerformed(evt);
            }
        });

        buttonGroup1.add(gdFemale);
        gdFemale.setText("Female");
        gdFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gdFemaleActionPerformed(evt);
            }
        });

        btDELETE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btDELETE.setText("DELETE");
        btDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDELETEActionPerformed(evt);
            }
        });

        btSAVE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btSAVE.setText("SAVE");
        btSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSAVEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btADD, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(gdMale))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gdFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btEDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btSAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(ibImage, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(gdMale)
                            .addComponent(gdFemale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btADD, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btEDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ibImage, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void updateFile() {
        try (PrintWriter pw = new PrintWriter(new FileWriter("D:/customers.txt"))) {
            for (Customers cus : dao.getAllCustomer()) {
                pw.println(cus.getId() + "," + cus.getName() + "," + cus.getPhone() + "," + (cus.isGender() ? "Male" : "Female") + "," + cus.getImage());
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    public void reset(){
        txtID.setText("");
        txtName.setText("");
        txtPhone.setText("");
        gdMale.isSelected();
        ibImage.setText("Image");
        ibImage.setIcon(null);
        strImage = null;
    }
    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void btADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btADDActionPerformed
           // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btADDActionPerformed

    private void gdMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gdMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gdMaleActionPerformed

    private void gdFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gdFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gdFemaleActionPerformed

    private void ibImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ibImageMouseClicked
        // TODO add your handling code here:
        try {
            JFileChooser jf = new JFileChooser();
            jf.showOpenDialog(null);
            File file = jf.getSelectedFile();
            Image img = ImageIO.read(file);
            strImage = file.getName();
            ibImage.setText("");
            int width = ibImage.getWidth();
            int height = ibImage.getHeight();
            ibImage.setIcon(new ImageIcon(img.getScaledInstance(width, height, 0)));
        } catch (Exception e) {
            System.out.println("Error: "+e.toString());
        }
    }//GEN-LAST:event_ibImageMouseClicked
    public boolean validateForm(){
        if(txtID.getText().isEmpty() || txtName.getText().isEmpty() ){
            return false;
        }
            return true;
        
    }
    public Customers getModel() throws ParseException{
        Customers cus = new Customers();
        cus.setId(txtID.getText());
        cus.setName(txtName.getText());
        boolean gd = false;
        if(gdMale.isSelected()){
            gd = true;
        }
        cus.setGender(gd);
        if(strImage == null){
            cus.setImage("NO AVATAR");
        }else{
            cus.setImage(strImage);
        }
        return cus;
    }
    private void btSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSAVEActionPerformed
        
    // TODO add your handling code here:
    if (validateForm()) {
        try {
            Customers cus = getModel();
            if (dao.add(cus) > 0) {
                // Ghi thông tin vào file CSV
                try (PrintWriter pw = new PrintWriter(new FileWriter("D:/customers.txt", true))) {
                    pw.println(cus.getId() + "," + cus.getName() + "," + cus.getPhone() + "," + (cus.isGender() ? "Male" : "Female") + "," + cus.getImage());
                } catch (IOException e) {
                    e.printStackTrace();
                }

                JOptionPane.showMessageDialog(this, "Save Success!");
                fillTable();
            }
        } catch (ParseException e) {
            e.printStackTrace();
        }
    } else {
        JOptionPane.showMessageDialog(this, "You have not entered enough information!");
    }

    }//GEN-LAST:event_btSAVEActionPerformed
    public void setModel(Customers cus){
        txtID.setText(cus.getId());
        txtName.setText(cus.getName());
        if(cus.isGender()){
            gdMale.isSelected();
        }else{
            gdFemale.isSelected();
        }
        // load hinh anh;
        ibImage.setText("");
        ImageIcon imgIcon = new ImageIcon(getClass().getResource("com/Bida/icon/"+cus.getImage()));
        Image img = imgIcon.getImage();
        img.getScaledInstance(ibImage.getWidth(), ibImage.getY(), 0);
    }
    private void dataCUSTOMERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataCUSTOMERMouseClicked
        // TODO add your handling code here:
        int id = dataCUSTOMER.rowAtPoint(evt.getPoint());
        String cusid = dataCUSTOMER.getValueAt(id, 0).toString();
        Customers cus = dao.getCusById(cusid);
    }//GEN-LAST:event_dataCUSTOMERMouseClicked

    private void btEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEDITActionPerformed
        // Kiểm tra tính hợp lệ của form
    if (validateForm()) {
        try {
            Customers cus = getModel();
            if (dao.update(cus) > 0) {
                // Cập nhật file CSV
                updateFile();
                JOptionPane.showMessageDialog(this, "Edit Success!");
                fillTable();
            }
        } catch (ParseException e) {
            e.printStackTrace();
        }
    } else {
        JOptionPane.showMessageDialog(this, "You have not entered enough information!");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btEDITActionPerformed

    private void btDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDELETEActionPerformed
    // Xóa thông tin khách hàng
    int row = dataCUSTOMER.getSelectedRow();
    if (row >= 0) {
        String cusId = dataCUSTOMER.getValueAt(row, 0).toString();
        if (dao.delete(cusId) > 0) {
            // Cập nhật file CSV
            updateFile();
            JOptionPane.showMessageDialog(this, "Delete Success!");
            fillTable();
        } else {
            JOptionPane.showMessageDialog(this, "Delete Failed!");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a row to delete!");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btDELETEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btADD;
    private javax.swing.JButton btDELETE;
    private javax.swing.JButton btEDIT;
    private javax.swing.JButton btSAVE;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable dataCUSTOMER;
    private javax.swing.JRadioButton gdFemale;
    private javax.swing.JRadioButton gdMale;
    private javax.swing.JLabel ibImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables

    private void updateFile() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
